version: "3.9"

services:
  golang:
    container_name: golang_container
    build:
      dockerfile: Dockerfile
    environment:
      - STAGE=${STAGE}
      - SQS_URL=${SQS_URL}
      - AWS_TOKEN=${AWS_TOKEN}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - 8080:8080
    restart: on-failure
